#!/usr/bin/env bash
# Canonical LBV catalog import caps — source from run scripts and cron lines.
# Convention: 0 = unlimited (avoid for production cron; use explicit caps below).

export PROFILES_PER_CITY="${PROFILES_PER_CITY:-250}"
export PROFILES_PER_STATE="${PROFILES_PER_STATE:-1250}"
export EROS_MAX_PAGES="${EROS_MAX_PAGES:-15000}"
export TRYST_MAX_PROFILES_PER_CITY="${TRYST_MAX_PROFILES_PER_CITY:-250}"
export TRYST_MAX_CITIES_PER_STATE="${TRYST_MAX_CITIES_PER_STATE:-5}"
export TRYST_MAX_LISTING_PAGES_PER_CITY="${TRYST_MAX_LISTING_PAGES_PER_CITY:-25}"
export STRICT_IMPORT_VERIFICATION_GATE="${STRICT_IMPORT_VERIFICATION_GATE:-1}"
export REVIEW_MATCH_LIMIT="${REVIEW_MATCH_LIMIT:-0}"
export IMPORT_ORCHESTRATOR_MAX_MINUTES="${IMPORT_ORCHESTRATOR_MAX_MINUTES:-180}"
